# Helper script to register external function imports with usethis.
# Run this script from the project root to update NAMESPACE imports.

usethis::use_import_from("tools", "R_user_dir")
usethis::use_import_from("utils", "read.fwf")
usethis::use_import_from("utils", "askYesNo")
usethis::use_import_from("utils", "unzip")
usethis::use_import_from("utils", "read.table")
usethis::use_import_from("utils", "type.convert")
usethis::use_import_from("stringr", "str_extract")
usethis::use_import_from("stringr", "str_starts")
usethis::use_import_from("stringr", "str_ends")
usethis::use_import_from("purrr", "map")
usethis::use_import_from("stats", "loess")
usethis::use_import_from("stats", "predict")
usethis::use_import_from("ggplot2", "standardise_aes_names")
usethis::use_import_from("readr", "read_delim")
usethis::use_import_from("httr", "user_agent")
usethis::use_import_from("httr", "GET")
usethis::use_import_from("data.table", "rbindlist")
usethis::use_import_from("data.table", "melt")
usethis::use_import_from("reshape2", "melt")
usethis::use_import_from("dplyr", "pivot_longer")
usethis::use_import_from("dplyr", "pivot_wider")
usethis::use_import_from("dplyr", "mutate")
usethis::use_import_from("magrittr", "%>%")
usethis::use_import_from("dplyr", "select")
usethis::use_import_from("dplyr", "mutate_at")
usethis::use_import_from("dplyr", "rename")
usethis::use_import_from("dplyr", "bind_rows")
usethis::use_import_from("dplyr", "group_by")
usethis::use_import_from("dplyr", "summarise")
usethis::use_import_from("dplyr", "group_by")
usethis::use_import_from("dplyr", "filter")
usethis::use_import_from("dplyr", "arrange")
usethis::use_import_from("dplyr", "rename")
usethis::use_import_from("dplyr", "nest")
usethis::use_import_from("dplyr", "unnest")
usethis::use_import_from("dplyr", "select")
usethis::use_import_from("dplyr", "slice")
usethis::use_import_from("dplyr", "distinct")
usethis::use_import_from("dplyr", "bind_rows")
usethis::use_import_from("utils", "download.file")
usethis::use_import_from("stringi", "stri_split_lines")
usethis::use_import_from("stringi", "stri_split_lines1")
usethis::use_import_from("stringi", "stri_split_fixed")
usethis::use_import_from("RCurl", "getURL")
usethis::use_import_from("curl", "new_handle")
usethis::use_import_from("curl", "handle_setopt")
usethis::use_import_from("data.table", "rbindlist")
usethis::use_import_from("data.table", "setDT")
usethis::use_import_from("lubridate", "ymd")
usethis::use_import_from("lubridate", "year")
usethis::use_import_from("lubridate", "month")
usethis::use_import_from("lubridate", "make_date")
usethis::use_import_from("sf", "st_crs")
usethis::use_import_from("sf", "st_as_sf")
usethis::use_import_from("fst", "write_fst")
usethis::use_import_from("fst", "read_fst")
usethis::use_import_from("readr", "read_csv")





