#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom curl handle_setopt
#' @importFrom curl new_handle
#' @importFrom data.table melt
#' @importFrom data.table rbindlist
#' @importFrom data.table setDT
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_at
#' @importFrom dplyr nest
#' @importFrom dplyr pivot_longer
#' @importFrom dplyr pivot_wider
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr unnest
#' @importFrom fst read_fst
#' @importFrom fst write_fst
#' @importFrom ggplot2 standardise_aes_names
#' @importFrom httr GET
#' @importFrom httr user_agent
#' @importFrom lubridate make_date
#' @importFrom lubridate month
#' @importFrom lubridate year
#' @importFrom lubridate ymd
#' @importFrom magrittr %>%
#' @importFrom purrr map
#' @importFrom RCurl getURL
#' @importFrom readr read_csv
#' @importFrom readr read_delim
#' @importFrom reshape2 melt
#' @importFrom sf st_as_sf
#' @importFrom sf st_crs
#' @importFrom stats loess
#' @importFrom stats predict
#' @importFrom stringi stri_split_fixed
#' @importFrom stringi stri_split_lines
#' @importFrom stringi stri_split_lines1
#' @importFrom stringr str_ends
#' @importFrom stringr str_extract
#' @importFrom stringr str_starts
#' @importFrom tools R_user_dir
#' @importFrom utils askYesNo
#' @importFrom utils download.file
#' @importFrom utils read.fwf
#' @importFrom utils read.table
#' @importFrom utils type.convert
#' @importFrom utils unzip
## usethis namespace: end
NULL
